.float jump_force;


.float main_xp;
.float add_point;
.float  xp_points;

// skills 

.float raw_armor_wearing_xp;
.float raw_melee_xp;
.float raw_accuracy_xp;
.float raw_explosive_xp;
.float raw_searching_xp;
.float raw_agility_xp;

// processed

.float armor_wearing_xp;
.float melee_xp;
.float accuracy_xp;
.float explosive_xp;
.float searching_xp;
.float agility_xp;


float RATE_MELEE_XP = 0.02;
float RATE_ACCURACY_XP = 0.025;
float RATE_EXPLOSIVE_XP = 0.02;
float RATE_ARMOR_XP = 0.1;
float RATE_SEARCHING_XP = 0.001;
float RATE_AGILITY_XP = 0.1;




.float w_mod_a;
.float w_mod_b;
.float w_mod_c;
.float w_mod_d;