void() initialize_stat_names =
{
    stat_weapon_names[WEAPON_AXE] = "Axe";
    stat_weapon_names[WEAPON_SHOTGUN] = "Shotgun";
    stat_weapon_names[WEAPON_SUPER_SHOTGUN] = "Super Shotgun";
    stat_weapon_names[WEAPON_3SHOTGUN] = "Three Shot";
    stat_weapon_names[WEAPON_NAILGUN] = "Nailgun";
    stat_weapon_names[WEAPON_SUPER_NAILGUN] = "Super Nailgun";
    stat_weapon_names[WEAPON_GRENADE_LAUNCHER] = "Grenade Launcher";
    stat_weapon_names[WEAPON_ROCKET_LAUNCHER] = "Rocket Launcher";
};